# Generated by Django 2.0.6 on 2018-07-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0010_auto_20180709_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='math_ppd',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (20, 20)], default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='reading_ppd',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (20, 20)], default=1),
        ),
    ]
