# Generated by Django 2.0.6 on 2018-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0012_auto_20180718_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='+15555555', max_length=10),
            preserve_default=False,
        ),
    ]
