# Generated by Django 2.0.6 on 2018-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0015_auto_20180718_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
