# Generated by Django 2.0.6 on 2018-07-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0020_auto_20180720_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_registration.Instructor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_discount_percent',
            field=models.IntegerField(choices=[(0, 0), (50, 50), (100, 100)], default=0),
        ),
    ]
