# Generated by Django 2.0.6 on 2018-08-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0021_auto_20180729_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
