# Generated by Django 2.0.6 on 2018-08-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0024_auto_20180802_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbystudent',
            name='school_year_end',
        ),
        migrations.RemoveField(
            model_name='lobbystudent',
            name='school_year_start',
        ),
        migrations.AddField(
            model_name='lobbystudent',
            name='parent_city',
            field=models.CharField(default='Birmingham', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobbystudent',
            name='school_years',
            field=models.CharField(choices=[('2018 - 2019', '2018 - 2019'), ('2019 - 2020', '2019 - 2020'), ('2020 - 2021', '2020 - 2021'), ('2021 - 2022', '2021 - 2022'), ('2022 - 2023', '2022 - 2023')], default='2018 - 2019', max_length=11),
            preserve_default=False,
        ),
    ]
