# Generated by Django 2.0.6 on 2018-08-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0025_auto_20180802_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbystudent',
            name='school_years',
        ),
        migrations.AddField(
            model_name='lobbystudent',
            name='school_year',
            field=models.CharField(choices=[('2018 - 2019', '2018 - 2019'), ('2019 - 2020', '2019 - 2020'), ('2020 - 2021', '2020 - 2021'), ('2021 - 2022', '2021 - 2022'), ('2022 - 2023', '2022 - 2023')], default='2018 - 2019', max_length=11),
        ),
    ]
