# Generated by Django 2.0.6 on 2018-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0026_auto_20180802_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbystudent',
            name='school_year',
            field=models.CharField(max_length=20),
        ),
    ]
