# Generated by Django 2.0.6 on 2018-08-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0027_auto_20180803_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbystudent',
            name='emergency_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
