# Generated by Django 2.0.6 on 2018-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0028_auto_20180803_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbystudent',
            name='parent_mobile_phone_number',
            field=models.CharField(max_length=14),
        ),
    ]
