# Generated by Django 2.0.6 on 2018-08-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0030_lobbystudent_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_registration.LobbyStudent'),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='apt_or_suite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='parent_apt_or_suite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='parent_home_phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='parent_mobile_phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='lobbystudent',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='math_ppd',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (20, 20)], default=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='reading_ppd',
            field=models.IntegerField(blank=True, choices=[(5, 5), (10, 10), (20, 20)], default=10, null=True),
        ),
    ]
