# Generated by Django 2.0.6 on 2018-08-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0031_auto_20180803_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_registration.LobbyStudent'),
        ),
    ]
