# Generated by Django 2.0.6 on 2018-08-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0032_auto_20180803_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbystudent',
            name='is_registered',
        ),
    ]
